### ISSUE TITLE
Alone decimal numbers are not interpreted for fractions

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/search#12]
https://mathematicator.com/search/4.0/2.0

FAILS:
![image](https://user-images.githubusercontent.com/2387790/82484154-ce6c3480-9ad9-11ea-9461-d90cb375dd9d.png)

![image](https://user-images.githubusercontent.com/2387790/82484119-c44a3600-9ad9-11ea-9085-497be2c0145d.png)

OK:
![image](https://user-images.githubusercontent.com/2387790/82484049-a54ba400-9ad9-11ea-9858-757af85cdf94.png)

**Comment by janbarasek** [comment]
I think this is error in mapper between Tokenizer (raw tokens) to Object Tokens.

All decimal numbers should be converted to fractions.

https://github.com/mathematicator-core/tokenizer/blob/master/src/TokensToObject.php#L51

Can you send PR?

**Comment by flokixdev** [comment]
@janbarasek Maybe later I will try to debug it, not my priority at this time.
