### ISSUE TITLE
Support LaTeX for search input

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/search#18]

**Comment by janbarasek** [comment]
I have been planning support for LaTeX for a long time. The solution is to implement new rules for tokenization and parsing. I think I could write it fast (maximum in a month).

Can you think of a regular expression to recognize that it's LaTeX to switch parsing mode?

**Comment by flokixdev** [comment]
@janbarasek See https://stackoverflow.com/a/14537848/1044198
