### ISSUE TITLE
Invalid proposion of solutions

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/search#22]
Input: 198+15=205

![image](https://user-images.githubusercontent.com/2387790/83979920-12509d80-a912-11ea-8649-37be61ba4503.png)

**Comment by janbarasek** [comment]
In last version it was correct.

![87B0C537-66D8-469E-AC78-7A3209543FF6](https://user-images.githubusercontent.com/4738758/83999224-9b8fc080-a962-11ea-9805-0d6f9e259891.jpeg)

**Comment by flokixdev** [comment]
![Screenshot_20200608-090706_Edge](https://user-images.githubusercontent.com/2387790/84001793-a567f280-a967-11ea-8097-26f1f8c2e62e.jpg)
