### ISSUE TITLE
Unhandled exception (query starting with an operator)

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/search#5]
There is some unhandled exception on Mathematicator that when I write a query starting with an operator other than minus (e.g. +2) then I see Server Error https://mathematicator.com/search/?q=%2B4

**Comment by janbarasek** [comment]
Because bug is in `TokensCalculator`:

<img width="1156" alt="Snímek obrazovky 2020-06-08 v 22 14 11" src="https://user-images.githubusercontent.com/4738758/84076037-62dcff00-a9d5-11ea-966b-07ae91bf3725.png">
