### ISSUE TITLE
Wrong multi-powers interpretation and result

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/search#6]
E.g. 5^2^3: https://mathematicator.com/search/5%5E2%5E3
![image](https://user-images.githubusercontent.com/2387790/80460435-2036fa00-8934-11ea-8b7a-72051b72b424.png)

Wrong interpretation and also result - see right interp. and result here: : https://www.wolframalpha.com/input/?i=5%5E2%5E3

**Comment by janbarasek** [comment]
@miloshavlicek I'm not sure which rule is mathematically correct.

Take a look at the calculation procedure:

![Snímek obrazovky 2020-04-28 v 9 42 50](https://user-images.githubusercontent.com/4738758/80460822-a18e8c80-8934-11ea-8a29-eb18e64763ce.png)

And Mac Spotlight:

![Snímek obrazovky 2020-04-28 v 9 43 41](https://user-images.githubusercontent.com/4738758/80460900-bff48800-8934-11ea-80b6-f0187bfe2d0a.png)
Anyway, there is an error in rendering the query interpretation.

**Comment by flokixdev** [comment]
@janbarasek The same result as Mac Spotlight is in Windows Calculator and Samsung Calculator.

However when I click [num] [pow] [num] [pow] [num] on my Casio calculator or on Google: https://www.google.com/search?q=5%5E2%5E3 there is the second result.

However, I am also not sure whether there is a rule about it.

**Comment by janbarasek** [comment]
@miloshavlicek I have created a new thread on the forum and I will make a correction later.

https://mathematicator.com/matematicke-forum/pravidlo-pro-retezove-umocnovani-cisel

**Comment by flokixdev** [comment]
@janbarasek I have created a question on Math StackExchange where I explain it more: https://math.stackexchange.com/questions/3647880/interpretation-of-multi-exponent-xyz-xyz-or-xyz/3648003

**Comment by flokixdev** [comment]
Similar issue is with negation vs exponentiation first: (e.g. -2^2)
[Google](https://www.google.com/search?q=-2%5E2), [WolframAlpha](https://www.wolframalpha.com/input/?i=-2%5E2): -4
[Mathematicator](https://mathematicator.com/search/-2%5E2): 4
